//! IDA 导出：`ida_script/addNames.py`（IDAPython 命名脚本）+ `ida_dart_struct.h`（结构头）。
//!
//! API 选择对齐 IDA 9.x（9.3/9.4 真机实测）且兼容 8.x：
//! - 命名/边界：`ida_name.set_name` / `ida_funcs.add_func`（typed API，8.x+ 均存在）；
//! - 结构导入：`ida_typeinf.parse_decls` 传**文件内容字符串**（9.x 的「路径 + PT_FILE」
//!   形式已失效，实测 str 内容形式 0.43s 解析完 2.2MB 结构头）；8.x 用二参形式回退；
//! - 生成的脚本体是「数据表 + 纯 Python 循环」（无版本相关语法，7.x-9.x 通用）；
//!   命名带 SN_NOWARN(0x80)，必然失败的 stub 假条目静默计数；产物文件不含中文。

use crate::analyzer::{Analyzer, LibGroups};
use crate::engine::restore::scrub_name;
use std::fmt::Write as _;
use std::path::Path;

/// 写 ida_script/addNames.py + ida_dart_struct.h，返回命名函数条数。
pub fn write(analyzer: &Analyzer, _libs: &LibGroups, out_dir: &Path) -> Result<usize, String> {
    let dir = out_dir.join("ida_script");
    std::fs::create_dir_all(&dir)
        .map_err(|e| format!("创建 ida_script 目录失败: {e}"))?;

    // 结构头：与 r2 同源（MIT 归因 + per-target DartThread/DartObjectPool）
    let hdr = crate::export::struct_hdr::build(analyzer);
    std::fs::write(dir.join("ida_dart_struct.h"), hdr)
        .map_err(|e| format!("写 ida_dart_struct.h 失败: {e}"))?;

    // 数据行：(offset, size, name)；与 addNames.r2 同口径，仅保留 code 表可达的函数
    let mut rows: Vec<(u64, u64, String)> = Vec::new();
    for (&ep, name) in &analyzer.name_by_ep {
        if !analyzer.func_eps.values().any(|(e, _)| *e == ep) {
            continue;
        }
        let clean = scrub_name(Some(name));
        if clean.is_empty() {
            continue;
        }
        let size = analyzer
            .func_eps
            .iter()
            .find(|(_, (e, _))| *e == ep)
            .map(|(_, (_, idx))| analyzer.code_size(*idx))
            .unwrap_or(0);
        rows.push((ep, size, format!("{clean}_{ep:x}")));
    }

    let mut py = String::new();
    py.push_str("#!/usr/bin/env python3\n");
    py.push_str("# Generated by dae — Dart AOT symbol import for IDA (IDAPython).\n");
    py.push_str("# Usage: in IDA, File -> Script file... and select this file.\n");
    py.push_str("# Data-driven: the NAMES table below is applied by a plain Python loop;\n");
    py.push_str("# no version-specific syntax, works on IDA 7.x through 9.x.\n");
    py.push_str("#\n");
    py.push_str("# Rebase: addresses are file offsets; every address is shifted by the image\n");
    py.push_str("# base (non-zero on executables such as macOS apps; 0 for ELF shared\n");
    py.push_str("# libraries like Android libapp.so).\n\n");
    py.push_str("import os\nimport idc\nimport ida_nalt\nimport ida_name\nimport ida_funcs\nimport ida_typeinf\n\n");
    py.push_str("print(\"[dae] importing Dart names into current IDB...\")\n");
    py.push_str("BN = ida_nalt.get_imagebase()\n");
    py.push_str("print(\"[dae] image base = {:#x}\".format(BN))\n\n");

    // 数据段
    let _ = write!(py, "# {} named functions: (offset, size, name); size == 0 = boundary unknown\n", rows.len());
    py.push_str("NAMES = [\n");
    for (ep, size, name) in &rows {
        let _ = write!(py, "    (0x{ep:x}, 0x{size:x}, \"{name}\"),\n");
    }
    py.push_str("]\n\n");

    // 应用循环：set_name 带 SN_NOWARN(0x80)，目标为文件头 tail byte 等不可命名地址时
    // 静默计数（去符号 exe 的快照回退场景必现），不再刷 "can't rename byte..." 告警
    py.push_str("n_named = 0\nn_failed = 0\n");
    py.push_str("for off, size, name in NAMES:\n");
    py.push_str("    ea = BN + off\n");
    py.push_str("    if ida_name.set_name(ea, name, 0x80):\n");
    py.push_str("        n_named += 1\n");
    py.push_str("    else:\n");
    py.push_str("        n_failed += 1\n");
    py.push_str("    if size > 0:\n");
    py.push_str("        ida_funcs.add_func(ea, ea + size)\n");
    py.push_str("print(\"[dae] names: {} named, {} failed\".format(n_named, n_failed))\n\n");

    // 结构导入
    py.push_str("def _create_dart_structs():\n");
    py.push_str("    \"\"\"Parse DartThread/DartObjectPool layouts from ida_dart_struct.h.\"\"\"\n");
    py.push_str("    hdr = os.path.join(os.path.dirname(os.path.abspath(__file__)), \"ida_dart_struct.h\")\n");
    py.push_str("    with open(hdr, \"r\", encoding=\"utf-8\", errors=\"replace\") as f:\n");
    py.push_str("        content = f.read()\n");
    py.push_str("    til = ida_typeinf.get_idati()\n");
    py.push_str("    rc = None\n");
    py.push_str("    for args in ((til, content, None, 0), (til, content)):\n");
    py.push_str("        try:\n");
    py.push_str("            rc = ida_typeinf.parse_decls(*args)\n");
    py.push_str("            break\n");
    py.push_str("        except TypeError:\n");
    py.push_str("            continue\n");
    py.push_str("    s_thread = idc.get_struc_id(\"DartThread\")\n");
    py.push_str("    s_pool = idc.get_struc_id(\"DartObjectPool\")\n");
    py.push_str("    print(\"[dae] structs: DartThread={}, DartObjectPool={} (parse_rc={})\".format(\n");
    py.push_str("        s_thread, s_pool, rc))\n");
    py.push_str("    if s_thread == idc.BADADDR or s_pool == idc.BADADDR:\n");
    py.push_str("        print(\"[dae] struct import failed - you can import ida_dart_struct.h manually via File -> Load file -> Parse C header file\")\n\n");
    py.push_str("_create_dart_structs()\n");
    py.push_str("print(\"[dae] done.\")\n");

    std::fs::write(dir.join("addNames.py"), py)
        .map_err(|e| format!("写 addNames.py 失败: {e}"))?;
    Ok(rows.len())
}
